apiVersion: v1
kind: LimitRange
metadata:
  name: cpu&memery-resources-constarint
spec:
  limits:
    - type: containers
      default:
        cpu: 500m # equals to 0.5
        memory: 1Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: 1
        memory: 2Gi
      min:
        cpu: 100m
        memory: 256Mi