apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    type: frontend
# namespace: dev # the pod will be created in the specified namespace
spec:
  containers:
    - name: nginx
      image: nginx