apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    type: frontend
  namespace: dev # the pod will be created in the specified namespace
spec:
  containers:
    - name: nginx
      image: nginx

      command:
        - some-commands
        - echo "Hello"

      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

  tolerations:
    - key: "color" 
      operator: "Equal"
      value: "Blue"
      effect: "NoSchedule"

  nodeSelector:
    size: large

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large 
                  - Medium
  
  schedulerName: my-custom-scheduler

  priorityClassName: high-priority