apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    type: frontend
  namespace: dev # the pod will be created in the specified namespace
spec:
  containers:
    - name: nginx
      image: nginx
      command:
        - some-commands
        - echo "Hello"
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:   # referencing the value from the configMap
              key: APP_COLOR
              name: app-config
            secretKeyRef:      # referencing the value from the secrets
              key: DB_HOST
              name: app-secret

      resources:
        requests:              # ensure the container gets mentioned amount of resources
          memory: "64Mi"
          cpu: "250m"
        limits:                # setting up the consumption limit
          memory: "128Mi"
          cpu: "500m"

    - name: log-agent
      image: log-agent
      ports:
        - containerPort: 8080

  initContainers:
    - name: init-myservice
      image: busybox
      command: ["sh", "-c", "git clone https://..."]

    - name: init-mydb
      image: busybox:1.28
      command: ["sh", "-c", "git clone https://..."]

  tolerations:                # setting up pod toleration against Node taint
    - key: "color" 
      operator: "Equal"
      value: "Blue"
      effect: "NoSchedule"

  nodeSelector:               # selects a node with specified labeled
    size: large

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large 
                  - Medium
  
  schedulerName: my-custom-scheduler

  priorityClassName: high-priority