apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type:  NodePort   # Can be NodePort, ClusterIP and LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:         # selects the pods which has below labels
    app: myapp  
    type: backend